const http = require('http');
const mysql = require('mysql2');

const PORT = 8080;

// 1. Configure your local MySQL Connection (💡 Local အတွက် တိုက်ရိုက်ပြင်ဆင်ထားသည်)
const db = mysql.createConnection({
    host: 'localhost',
    user: 'root',                  // 👈 အလွတ်မထားဘဲ 'root' လို့ တိုက်ရိုက်ထည့်ထားပါတယ်
    password: 'MYsql2525#', // 👈 ⚠️ သင့်ရဲ့ MySQL Workbench Password ကို ဒီမှာ ချိန်းပေးပါ (XAMPP ဆိုရင် '' အလွတ်ထားပါ)
    database: 'shwe_ramen'      // 👈 ⚠️ သင့် MySQL ထဲက database နာမည်နဲ့ ကိုက်ညီအောင် ပြင်ပေးပါ
});

// Connect to MySQL
db.connect((err) => {
    if (err) {
        console.error('❌ Error connecting to MySQL database:', err.message);
        return;
    } 
    console.log('✅ Connected to the MySQL database successfully.');
});

// 2. Create the Web Server
const server = http.createServer((req, res) => {
    // Set up CORS headers so your frontend index.html can communicate with it
    res.setHeader('Access-Control-Allow-Origin', '*');
    res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS');
    res.setHeader('Access-Control-Allow-Headers', 'Content-Type');

    // Handle the browser safety check (Preflight)
    if (req.method === 'OPTIONS') {
        res.writeHead(204);
        res.end();
        return;
    }

    // Handle incoming customer orders
    if (req.method === 'POST' && req.url === '/api/order') {
        let body = '';

        // Collect incoming JSON data packets
        req.on('data', chunk => {
            body += chunk.toString();
        });

        req.on('end', () => {
            try {
                const payload = JSON.parse(body);
                const { customerName, tableNumber, totalPrice, items } = payload;

                // Start an ACID transaction block for safe database insertion
                db.beginTransaction((err) => {
                    if (err) throw err;

                    // Insert order metadata into 'orders' table
                    const orderQuery = `INSERT INTO orders (customer_name, table_number, total_price) VALUES (?, ?, ?)`;
                    db.query(orderQuery, [customerName, tableNumber, totalPrice], (err, result) => {
                        if (err) {
                            return db.rollback(() => { throw err; });
                        }

                        // Capture the auto-incremented primary key generated by MySQL
                        const orderId = result.insertId;

                        // Prepare items to be added as rows
                        const itemQuery = `INSERT INTO order_items (order_id, item_name) VALUES ?`;
                        const itemValues = items.map(itemName => [orderId, itemName]);

                        // Insert all chosen items into 'order_items' table
                        db.query(itemQuery, [itemValues], (err) => {
                            if (err) {
                                return db.rollback(() => { throw err; });
                            }

                            // Commit changes safely to the hardware disk
                            db.commit((err) => {
                                if (err) {
                                    return db.rollback(() => { throw err; });
                                }
                                console.log(`🚀 MySQL Success: Stored Order #${orderId}`);
                                
                                res.writeHead(200, { 'Content-Type': 'text/plain; charset=UTF-8' });
                                res.end('注文完了です。ありがとうございます！');
                            });
                        });
                    });
                });

            } catch (error) {
                console.error('Processing error:', error);
                res.writeHead(500, { 'Content-Type': 'text/plain' });
                res.end('Server internal processing error.');
            }
        });
    } else {
        res.writeHead(404, { 'Content-Type': 'text/plain' });
        res.end('Not Found');
    }
});

// Start listening for network traffic
server.listen(PORT, () => {
    console.log(`🚀 SHWE Ramen JavaScript Server active at http://localhost:${PORT}`);
});